#if defined _store_included
 #endinput
#endif
#define _store_included

#include <store/store-core>
#include <store/store-backend>
#include <store/store-inventory>
#include <store/store-shop>
#include <store/store-loadouts>
#include <store/store-logging>

//External Includes
#include <multicolors>

//Optional Includes
#undef REQUIRE_PLUGIN
#include <updater>

#define STORE_AUTHORS "Alongub, Keith Warren(Drixevel), Arrow768"
#define STORE_URL "https://github.com/SourceMod-Store/store"
#define STORE_VERSION "1.2 Final"

#define STORE_PREFIX "\x04[Store] \x01"